import Head from "next/head";
import { useState, useEffect } from "react";
import styles from "../styles/Home.module.css";
import { GetStaticProps } from "next";
import Banner from "components/Banner";
import Link from "next/link";
import { useTranslation, Trans } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale ?? "en", [
        "common",
        "navigation",
      ])),
    },
  };
};

interface HomeProps {
  _nextI18Next: {
    initialLocale: string;
  };
}

const Home: React.FC<HomeProps> = ({ _nextI18Next }) => {
  const [locale, setLocale] = useState<string>();

  useEffect(() => {
    setLocale(_nextI18Next.initialLocale);
  }, [_nextI18Next.initialLocale]);

  const { t } = useTranslation("common");
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner title={t("mainTitle")} subtitle={t("mainSubtitle")}>
        <Link locale={locale} href="/apartments" className="btn-primary">
          <button className="capitalize tracking-widest">{t("btn1")}</button>
        </Link>
      </Banner>
      <h2>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum itaque
        mollitia incidunt id magnam ratione quidem quis culpa rem ab harum sed,
        laboriosam dignissimos dicta nobis. Nisi minima nihil libero saepe
        dolorem eum adipisci quasi aperiam accusantium ea explicabo delectus
        laborum voluptatum consequuntur sit placeat incidunt, similique qui
        nulla. Sequi ipsum vitae voluptas minima hic blanditiis facere fugiat
        ducimus molestias odio dolore voluptatum error nam modi, tempore labore
        quaerat excepturi. Illo quaerat provident iusto fugiat facere quam,
        aliquid quod impedit facilis culpa esse magni quo animi dolorum quasi
        saepe in? Enim, quaerat vitae consectetur at natus odit quod veritatis
        nihil, necessitatibus, eius repudiandae iure iste similique! Cumque
        labore vitae facilis amet! Inventore in non sint quisquam minus modi
        consequatur architecto beatae cum, praesentium, quis libero veniam,
        quibusdam harum nemo sunt repellat neque labore aliquam reprehenderit.
        Ex dolorum, suscipit tenetur blanditiis, mollitia facere explicabo
        incidunt pariatur repellendus fuga minus ut rerum totam quos ratione
        adipisci ea, magni alias molestiae rem qui quia dolores odit? Facere,
        numquam earum odio beatae molestias doloremque provident aliquid ad
        dolorum eligendi quibusdam quae unde at itaque veniam obcaecati sit. Ab
        dolores, sequi similique, odit sint facilis possimus praesentium
        incidunt iste, ducimus iusto odio tenetur. Repudiandae, esse.
      </h2>
      <h2>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum itaque
        mollitia incidunt id magnam ratione quidem quis culpa rem ab harum sed,
        laboriosam dignissimos dicta nobis. Nisi minima nihil libero saepe
        dolorem eum adipisci quasi aperiam accusantium ea explicabo delectus
        laborum voluptatum consequuntur sit placeat incidunt, similique qui
        nulla. Sequi ipsum vitae voluptas minima hic blanditiis facere fugiat
        ducimus molestias odio dolore voluptatum error nam modi, tempore labore
        quaerat excepturi. Illo quaerat provident iusto fugiat facere quam,
        aliquid quod impedit facilis culpa esse magni quo animi dolorum quasi
        saepe in? Enim, quaerat vitae consectetur at natus odit quod veritatis
        nihil, necessitatibus, eius repudiandae iure iste similique! Cumque
        labore vitae facilis amet! Inventore in non sint quisquam minus modi
        consequatur architecto beatae cum, praesentium, quis libero veniam,
        quibusdam harum nemo sunt repellat neque labore aliquam reprehenderit.
        Ex dolorum, suscipit tenetur blanditiis, mollitia facere explicabo
        incidunt pariatur repellendus fuga minus ut rerum totam quos ratione
        adipisci ea, magni alias molestiae rem qui quia dolores odit? Facere,
        numquam earum odio beatae molestias doloremque provident aliquid ad
        dolorum eligendi quibusdam quae unde at itaque veniam obcaecati sit. Ab
        dolores, sequi similique, odit sint facilis possimus praesentium
        incidunt iste, ducimus iusto odio tenetur. Repudiandae, esse.
      </h2>
      <h2>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum itaque
        mollitia incidunt id magnam ratione quidem quis culpa rem ab harum sed,
        laboriosam dignissimos dicta nobis. Nisi minima nihil libero saepe
        dolorem eum adipisci quasi aperiam accusantium ea explicabo delectus
        laborum voluptatum consequuntur sit placeat incidunt, similique qui
        nulla. Sequi ipsum vitae voluptas minima hic blanditiis facere fugiat
        ducimus molestias odio dolore voluptatum error nam modi, tempore labore
        quaerat excepturi. Illo quaerat provident iusto fugiat facere quam,
        aliquid quod impedit facilis culpa esse magni quo animi dolorum quasi
        saepe in? Enim, quaerat vitae consectetur at natus odit quod veritatis
        nihil, necessitatibus, eius repudiandae iure iste similique! Cumque
        labore vitae facilis amet! Inventore in non sint quisquam minus modi
        consequatur architecto beatae cum, praesentium, quis libero veniam,
        quibusdam harum nemo sunt repellat neque labore aliquam reprehenderit.
        Ex dolorum, suscipit tenetur blanditiis, mollitia facere explicabo
        incidunt pariatur repellendus fuga minus ut rerum totam quos ratione
        adipisci ea, magni alias molestiae rem qui quia dolores odit? Facere,
        numquam earum odio beatae molestias doloremque provident aliquid ad
        dolorum eligendi quibusdam quae unde at itaque veniam obcaecati sit. Ab
        dolores, sequi similique, odit sint facilis possimus praesentium
        incidunt iste, ducimus iusto odio tenetur. Repudiandae, esse.
      </h2>
    </div>
  );
};

export default Home;
