import Head from "next/head";
import { useState, useEffect } from "react";
import { GetStaticProps } from "next";
import Banner from "components/Banner";
import Link from "next/link";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import CardLayout from "components/CardLayout";
import Card from "components/Card";
import resCardImage from "../public/images/03Res.jpg";
import accCardImage from "../public/images/c10.jpg";
import funCardImage from "../public/images/c16.jpg";
import homeCardImage from "../public/images/home.jpg";
import Services from "components/Services";

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale ?? "en", [
        "common",
        "navigation",
      ])),
    },
  };
};

interface HomeProps {
  _nextI18Next: {
    initialLocale: string;
  };
}

const Home: React.FC<HomeProps> = ({ _nextI18Next }) => {
  const [locale, setLocale] = useState<string>();

  useEffect(() => {
    setLocale(_nextI18Next.initialLocale);
  }, [_nextI18Next.initialLocale]);

  const { t } = useTranslation("common");

  const cards = [
    {
      imageSrc: resCardImage,
      title: t("cuisine"),
      description: t("cuisineDesc"),
    },
    {
      imageSrc: accCardImage,
      title: t("hospitality"),
      description: t("hospitalityDesc"),
    },
    {
      imageSrc: funCardImage,
      title: t("fun"),
      description: t("funDesc"),
    },
    {
      imageSrc: homeCardImage,
      title: t("acc"),
      description: t("accDesc"),
    },
  ];

  return (
    <div className="bg-homeBackgroundColor bg-opacity-40">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="-mt-24">
        <Banner
          heroType="bg-mainHero"
          title={t("mainTitle")}
          subtitle={t("mainSubtitle")}
        >
          <Link locale={locale} href="/apartments" className="btn-primary">
            <button className="capitalize tracking-widest">{t("btn1")}</button>
          </Link>
        </Banner>
      </div>
      <Services cards={cards} />
    </div>
  );
};

export default Home;
